name: 'niloomid_banking_dv'
version: '1.0.0'
config-version: 2

profile: 'niloomid_snowflake'

# Updated for dbt v1.x+ compatibility
model-paths: ["models"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["data"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  niloomid_banking_dv:
    # --- STAGING LAYER ---
    staging:
      +schema: stg
      +materialized: view

    # --- RAW VAULT LAYER ---
    vault:
      hubs:
        +schema: hub
        +materialized: incremental
        +on_schema_change: append_new_columns

      links:
        +schema: link
        +materialized: incremental
        +on_schema_change: append_new_columns

      satellites:
        +schema: sat
        +materialized: incremental
        +on_schema_change: append_new_columns

    # --- REPORTING LAYER ---
    marts:
      +schema: mart
      +materialized: table  # Tables are faster for BI tools to query than views        
        
## This defines staging, hub, link, satellite schemas, materialization types, and project paths.
# Incremental Materialization: By switching Hubs, Links, and Satellites to incremental, dbt only processes new or changed data since the last run. For a bank with millions of daily transactions, this can reduce your Snowflake credit burn by over 80%.

# Schema Evolution: Adding on_schema_change: append_new_columns allows your warehouse to grow. If the source system adds a new field (like "Secondary Email"), dbt will automatically add that column to your Snowflake table without failing the pipeline.

# Modernized Paths: Using model-paths and seed-paths ensures your project works with the latest dbt features and avoids "deprecated" warnings.
