name: 'banking_vault'
version: '1.0.0'
config-version: 2

profile: 'banking_vault'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  load_datetime: "{{ run_started_at }}"
  source_system: "CORE_BANKING"

models:
  banking_vault:
    +materialized: view
    +schema: raw
    
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
      snowflake_warehouse: TRANSFORM_S_WH
      
    vault:
      +materialized: incremental
      +schema: vault
      +tags: ["vault", "incremental"]
      
      hubs:
        +materialized: incremental
        +unique_key: hub_key
        +on_schema_change: fail
        
      links:
        +materialized: incremental
        +unique_key: link_key
        +on_schema_change: fail
        
      satellites:
        +materialized: incremental
        +unique_key: ["hub_key", "load_datetime"]
        +on_schema_change: append_new_columns
        
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
      snowflake_warehouse: TRANSFORM_M_WH

on-run-start:
  - "{{ log('Starting dbt run at ' ~ run_started_at, info=True) }}"

on-run-end:
  - "{{ log('Completed dbt run at ' ~ run_started_at, info=True) }}"

seeds:
  banking_vault:
    +schema: seeds
    +quote_columns: false
