# dbt/profiles.yml
niloomid_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: NILOOMID_DEV
      warehouse: COMPUTE_WH
      schema: STG
      threads: 4

###How to Load the Secrets
##Before running dbt, you need to "export" these variables so dbt can see them. You can do this in your terminal:
# Load the variables from .env into your current session
# export $(xargs < .env)

# # Now run dbt
# cd dbt
# dbt debug
